#!/usr/bin/env bash

jupyter nbconvert --to slides index.ipynb --reveal-prefix=reveal.js \
  --SlidesExporter.reveal_theme=serif \
  --SlidesExporter.reveal_scroll=True \
  --SlidesExporter.reveal_transition=none \
